drop schema public CASCADE;
create schema public;

create table customers
(
    id      integer generated by default as identity
        primary key,
    name    varchar(255) not null,
    address varchar(255),
    phone   varchar(50),
    email   varchar(255)
);

alter table customers
    owner to testuser;

create unique index customers_email_key
    on customers (email);

create table paper
(
    id           integer generated by default as identity
        primary key,
    name         varchar(255)          not null,
    discontinued boolean default false not null,
    stock        integer default 0     not null,
    price        double precision      not null,
    picture      varchar(1000)         not null,
    description  varchar(255)          not null
);

alter table paper
    owner to testuser;

create unique index unique_product_name
    on paper (name);

create table properties
(
    id            integer generated by default as identity
        primary key,
    property_name varchar(255) not null
);

alter table properties
    owner to testuser;

create table orders
(
    id            integer generated by default as identity
        primary key,
    order_date    timestamp with time zone default CURRENT_TIMESTAMP            not null,
    delivery_date date,
    status        varchar(50)              default 'pending'::character varying not null,
    total_amount  double precision                                              not null,
    customer_id   integer
        references customers
            on delete cascade
);

alter table orders
    owner to testuser;

create index "IX_orders_customer_id"
    on orders (customer_id);

create table paper_properties
(
    paper_id    integer not null
        references paper,
    property_id integer not null
        references properties,
    primary key (paper_id, property_id)
);

alter table paper_properties
    owner to testuser;

create index "IX_paper_properties_property_id"
    on paper_properties (property_id);

create table order_entries
(
    id         integer generated by default as identity
        primary key,
    quantity   integer not null,
    product_id integer
        references paper,
    order_id   integer
        references orders
);

alter table order_entries
    owner to testuser;

create index "IX_order_entries_order_id"
    on order_entries (order_id);

create index "IX_order_entries_product_id"
    on order_entries (product_id);

